Changed everything

diff --git a/lib/util b/lib/util
--- a/lib/util
+++ b/lib/util
@@ -1,96 +1,104 @@
 #!/bin/bash
-# Utility functions for use in the cartridge scripts.
 
-source $OPENSHIFT_CARTRIDGE_SDK_BASH
-
-function wait_for_stop {
-  pid=$1
-  for i in {1..300}
-  do
-    if `ps --pid $pid > /dev/null 2>&1`
-    then
-      # only print every second
-      [ $((100 % 10)) -eq 0 ] && echo "Waiting for stop to finish"
-      sleep .1
-    else
-      break
-    fi
-  done
+# Retrieve the installed Node.js version (if any)
+function nodejs_version {
+  if which node > /dev/null; then
+    local VERSION_STRING="$(node --version)"
+    echo "${VERSION_STRING#v}"
+  fi
 }
 
-function set-configuration {
-  version="$1"
-  type="${2:-native}"
-  scl_string="${3}"
-  env_dir="${OPENSHIFT_NODEJS_DIR}/env"
+# Update Node.js
+function update_nodejs {
+  # Select the wanted Node.js version
+  if [ -n "$NODE_VERSION" ]; then
+    local WANTED="resolve/$NODE_VERSION"
+  elif [ -f "${OPENSHIFT_REPO_DIR}.openshift/NODE_VERSION" ]; then
+    local WANTED="resolve/$(cat "${OPENSHIFT_REPO_DIR}.openshift/NODE_VERSION")"
+  else
+    local WANTED="v0.12.0"
+  fi
 
-  case "$type" in
-    scl)
-      local npm_bin=$(echo -n "${OPENSHIFT_REPO_DIR}node_modules/.bin")
-      local node_bin=$(echo -n "${OPENSHIFT_HOMEDIR}/.node_modules/.bin")
-      local scl_bin=$(dirname $(scl enable $scl_string "which node"))
+  local VERSION_URL="https://semver.io/node/$WANTED"
+  local LATEST="$(curl --silent --max-time 5 "$VERSION_URL")"
 
-      echo "${npm_bin}:${node_bin}:${scl_bin}" >$OPENSHIFT_NODEJS_DIR/env/OPENSHIFT_NODEJS_PATH_ELEMENT
+  if [ -z "$LATEST" ]; then
+    echo "Could not retrieve Node.js version information from $VERSION_URL"
+    return 1
+  fi
 
-      local ld_path=$(LD_LIBRARY_PATH="" scl enable $scl_string "printenv LD_LIBRARY_PATH")
-      set_env_var 'OPENSHIFT_NODEJS_LD_LIBRARY_PATH_ELEMENT' $ld_path $env_dir
+  # Do not update if not needed
+  if [ "$(nodejs_version)" = "$LATEST" ]; then
+    return
+  fi
 
-      local man_path=$(MANPATH="" scl enable $scl_string "printenv MANPATH")
-      path_append $MANPATH $man_path >$OPENSHIFT_NODEJS_DIR/env/MANPATH
-      ;;
-    native)
-      rm -f $OPENSHIFT_NODEJS_DIR/env/{LD_LIBRARY_PATH,MANPATH}
-      echo -n "${OPENSHIFT_REPO_DIR}node_modules/.bin/:${OPENSHIFT_HOMEDIR}/.node_modules/.bin" > $OPENSHIFT_NODEJS_DIR/env/OPENSHIFT_NODEJS_PATH_ELEMENT
-      ;;
-  esac
+  local ARCHIVE_URL="https://nodejs.org/dist/v$LATEST/node-v$LATEST-linux-x64.tar.gz"
+  local ARCHIVE="$(mktemp)"
+  local DIRECTORY="${OPENSHIFT_DATA_DIR}.nodejs"
+
+  # Download
+  if ! curl -L -o "$ARCHIVE" "$ARCHIVE_URL"; then
+    return 1
+  fi
+
+  # Install
+  rm -rf "$DIRECTORY"
+  mkdir "$DIRECTORY"
+  tar xzvf "$ARCHIVE" --strip-components 1 -C "$DIRECTORY"
+
+  # Remove downloaded archive
+  rm "$ARCHIVE"
+
+  # Output result
+  echo "Node.js updated to $(nodejs_version)"
 }
 
-function parse_args {
-  while :
-  do
-    case $1 in
-      -h | --help | -\?)
-        echo "usage: $0 [--version[=]<value>]"
-        exit 0
-        ;;
-      -v | --version)
-        version=$2     # You might want to check if you really got VERSION
-        shift 2
-        ;;
-      --version=*)
-        version=${1#*=}        # Delete everything up till "="
-        shift
-        ;;
-      --) # End of all options
-        shift
-        break
-        ;;
-      -*)
-        echo "WARN: Unknown option... Exiting: $1" >&2
-        exit 1
-        ;;
-      *)  # no more options. Stop while loop
-        break
-        ;;
-    esac
-  done
+# Retrieve the latest package version matching the given semver range
+function remote_version {
+  local PACKAGE_URL="$(npm config get registry)$1/$2"
+  local PACKAGE="$(curl --silent --max-time 5 "$PACKAGE_URL")"
+  node --print --eval "($PACKAGE).version"
 }
 
-function link_global_modules {
-  OPENSHIFT_NODEJS_VERSION=$1
-  pushd $OPENSHIFT_NODEJS_DIR > /dev/null
-    # Global modules good to have
-    npmgl=$(grep "^\s*[^#\s]" $OPENSHIFT_NODEJS_DIR/versions/$OPENSHIFT_NODEJS_VERSION/configuration/npm_global_module_list | sort -u)
+# Retrieve the installed version of the given global package (if any)
+function local_version {
+  NODE_PATH="${OPENSHIFT_DATA_DIR}.nodejs/lib/node_modules" \
+    node --print --eval "require('$1/package.json').version" 2> /dev/null
+}
 
-    # Available global modules; only match top-level npm packages
-    global_modules=$(nodejs_context "npm ls -g 2> /dev/null" | perl -ne 'print "$1\n" if /^\S+\s(\S+)\@[\d\.-]+/' | sort -u)
+# Update npm
+function update_npm {
+  # Select the wanted npm version
+  if [ -n "$NPM_VERSION" ]; then
+    local WANTED="$NPM_VERSION"
+  elif [ -f "${OPENSHIFT_REPO_DIR}.openshift/NPM_VERSION" ]; then
+    local WANTED="$(cat "${OPENSHIFT_REPO_DIR}.openshift/NPM_VERSION")"
+  else
+    local WANTED="2.5.1"
+  fi
 
-    # List all modules in common
-    module_list=$(comm -12 <(echo "${global_modules}") <(echo "${npmgl}") | tr '\n' ' ')
+  local LATEST="$(remote_version npm "$WANTED")"
 
-    # Link the modules
-    nodejs_context "npm link $module_list &> /dev/null"
-  popd > /dev/null
+  if [ -z "$LATEST" ]; then
+    echo "Could not retrieve npm version information from the npm registry"
+    return 1
+  fi
+
+  # Do not update if not needed
+  if [ "$(npm --version)" = "$LATEST" ]; then
+    return
+  fi
+
+  # Update
+  npm install -g "npm@$LATEST"
+
+  # Output result
+  echo "Npm updated to $(npm --version)"
+}
+
+function is_running {
+  local PID="$(cat "$1" 2> /dev/null)"
+  [ -n "$PID" ] && kill -0 "$PID" 2> /dev/null
 }
 
 # Update PM2
@@ -101,7 +109,7 @@ function update_pm2 {
   elif [ -f "${OPENSHIFT_REPO_DIR}.openshift/PM2_VERSION" ]; then
     local WANTED="$(cat "${OPENSHIFT_REPO_DIR}.openshift/PM2_VERSION")"
   else
-    local WANTED="latest"
+    local WANTED="2.0.18"
   fi
 
   local LATEST="$(remote_version pm2 "$WANTED")"
@@ -136,171 +144,20 @@ function update_pm2 {
   echo "PM2 updated to $(local_version pm2)"
 }
 
-# Check if the 'use_npm' marker is present
-#
-function use_npm() {
-  [ -f ${OPENSHIFT_REPO_DIR}.openshift/markers/use_npm ]
+# Update Node.js, npm and PM2
+function update_all {
+  update_nodejs \
+    && update_npm \
+    && update_pm2
 }
 
-# This is the full path for pm2 in its SCL context
-function pm2_bin() {
-  nodejs_context "which pm2"
-}
+# Load PM2 variables from the repository to the environment
+function load_pm2_env {
+  if [ -z "$PM2_ENTRY_POINT" ] && [ -f "${OPENSHIFT_REPO_DIR}.openshift/PM2_ENTRY_POINT" ]; then
+    export PM2_ENTRY_POINT="$(cat "${OPENSHIFT_REPO_DIR}.openshift/PM2_ENTRY_POINT")"
+  fi
 
-function node_bin() {
-  nodejs_context "which node"
-}
-
-# All PIDs running node (including pm2)
-# Need to combine double slashes in case our PATH contains them
-#
-function node_pids() {
-  ps -u $(id -u) -o pid= -o cmd= | grep -e '[0-9]\{1,\}\snode\s' | sed -e 's#//#/#g'
-}
-
-# Only PIDs with node running pm2
-#
-function pm2_pid() {
-  pids=$(node_pids)
-  sup_exe=$(pm2_bin)
-  echo "${pids}" | awk "/${sup_exe//\//\/}/ {print \$1}"
-}
-
-# Only node PIDs without pm2
-#
-function node_pid() {
-  pids=$(node_pids)
-  sup_exe=$(pm2_bin)
-  echo "${pids}" | awk "!/${sup_exe//\//\/}/ {print \$1}"
-}
-
-# If pm2_pid is empty then assume cartridge is running using npm enabled
-#
-function cartridge_pid() {
-  if [ -z "$(pm2_pid)" ]; then
-    node_pid
-  else
-    pm2_pid
+  if [ -z "$PM2_INSTANCES" ] && [ -f "${OPENSHIFT_REPO_DIR}.openshift/PM2_INSTANCES" ]; then
+    export PM2_INSTANCES="$(cat "${OPENSHIFT_REPO_DIR}.openshift/PM2_INSTANCES")"
   fi
 }
-
-# check if the pidfile exists.
-# if it does not exist, look for the node or pm2 process 
-# and recreate the pidfile if the process exists
-function cartridge_pidfile_exists() {
-  if [ -f "$OPENSHIFT_NODEJS_PID_DIR/cartridge.pid" ]; then
-    return 0
-  else
-    cart_pid=$(cartridge_pid)
-    if [ -n "${cart_pid}" ]; then
-      echo ${cart_pid} > $OPENSHIFT_NODEJS_PID_DIR/cartridge.pid
-      return 0
-    else
-      return 1
-    fi
-  fi
-}
-
-function is_node_running() {
-    cartridge_pidfile_exists || return 1
-
-    nodepid=$(cat "${OPENSHIFT_NODEJS_PID_DIR}/cartridge.pid")
-    [ -n "$nodepid" ]  ||  return 1
-
-    node_command=$(ps --no-heading -ocmd -p $nodepid | sed -e 's#//#/#g')
-
-    # Ensure this is not a pm2 process
-    if [[ -n "$node_command" && ! "${node_command}" =~ $(pm2_bin) ]]; then
-       return 0
-    fi
-
-    return 1
-}
-
-function is_pm2_running() {
-    # cartridge_pidfile_exists || return 1
-
-    nodepid=$(cat "${PM2_HOME}/pm2.pid")
-    if [ -n "$nodepid" ]; then
-      return 1
-    else
-      return 0
-    fi
-
-    # #  Is the pid a pm2 process.
-    # if [[ $(ps --no-heading -ocmd -p $nodepid | sed -e 's#//#/#g') =~ $(pm2_bin) ]]; then
-    #    #  Yes, the app server is a pm2 process.
-    #    return 0
-    # fi
-}
-
-function is_silent() {
-  if [ -f "${OPENSHIFT_REPO_DIR}.openshift/markers/SILENT" ]; then
-    return 1
-  else
-    return 0
-  fi
-}
-
-function is_cartridge_running() {
-  is_pm2_running || is_node_running
-}
-
-function print_missing_package_json_warning() {
-       cat <<DEPRECATED
-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-  It is highly recommended that you add a package.json
-  file to your application.
-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-DEPRECATED
-}
-
-function print_deprecation_warning() {
-       cat <<DEPRECATED
-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-
-  The use of deplist.txt is being deprecated and will soon
-  go away. For the short term, we will continue to support
-  installing the Node modules specified in the deplist.txt
-  file. But please be aware that this will soon go away.
-
-  It is highly recommended that you use the package.json
-  file to specify dependencies on other Node modules.
-
-!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
-DEPRECATED
-}
-
-function is_node_module_installed() {
-    module_name=${1:-""}
-    if [ -n "$module_name" ]; then
-        pushd "$OPENSHIFT_NODEJS_DIR" > /dev/null
-        if [ -d $m ] ; then
-            popd > /dev/null
-            return 0
-        fi
-        popd > /dev/null
-    fi
-
-    return 1
-}
-
-function get_main_script_from_package_json() {
-    nodejs_context "node" <<NODE_EOF
-try {
-  var zmain = require('$OPENSHIFT_REPO_DIR/package.json').main;
-  if (typeof zmain === 'undefined') {
-    console.log('server.js');
-  }
-  else {
-    console.log(zmain);
-  }
-} catch(ex) {
-  console.log('server.js');
-}
-NODE_EOF
-
-}  #  End of function  get_main_script_from_package_json.
-
-
-# vim: ft=sh
